name = "AlgebraicDynamics"
uuid = "5fd6ff03-a254-427e-8840-ba658f502e32"
authors = ["James Fairbanks", "Sophie Libkind"]
version = "0.2.2"

[deps]
Catlab = "134e5e36-593f-5add-ad60-77f754baafbe"
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
Compose = "a81c6b42-2e10-5240-aca2-a61377ecd94b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearMaps = "7a12625a-238d-50fd-b39a-03d52299707e"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[weakdeps]
AlgebraicPetri = "4f99eebe-17bf-4e98-b6a1-2c4f205a959b"
DelayDiffEq = "bcd4f6db-9728-5f36-b5f7-82caef46ccdb"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[extensions]
AlgebraicDynamicsAlgebraicPetriExt = "AlgebraicPetri"
AlgebraicDynamicsDelayDiffEqExt = "DelayDiffEq"
AlgebraicDynamicsOrdinaryDiffEqExt = "OrdinaryDiffEq"
AlgebraicDynamicsPlotsExt = "Plots"

[compat]
AlgebraicPetri = "0.9"
Catlab = "0.15, 0.16"
ComponentArrays = "0.15"
Compose = "^0.9.1"
DelayDiffEq = "5"
LinearAlgebra = "1.9"
LinearMaps = "^3.1.0"
OrdinaryDiffEq = "^5.49.0, 6"
Plots = "^1.10.0"
RecipesBase = "1"
RecursiveArrayTools = "^2.10.0"
Reexport = "1"
SciMLBase = "2"
StaticArrays = "0.12, 1.0"
julia = "1.9"
